### ISSUE TITLE
Error during parse binary warc package

### ISSUE THREAD

**Issue by LastPossum** [ChrisCates/CommonCrawler#6]
I found that current CommonCrawler implementation returns wrong result if a warc file contains binary parts. 

It happen beacause of bufio.Scanner: according to golang documentation: 'Scanning stops unrecoverably at EOF, the first I/O error, or a token too large to fit in the buffer."  And I think its the third case. One can check this with following commands: "cat -v path_to_file | grep some_word" vs "cat path_to_file | grep some_word" on any warc file with large binary sections.

**Comment by LastPossum** [comment]
I'll fix it by myself, it anyone wouldn't mind

**Comment by ChrisCates** [comment]
@LastPossum, thanks, man! Appreciate looking into those edge cases!
